DATA_ROOT_DIRECTORY = 'D:\\BigData\\cellinfluid\\TrackingData\\'
FILE_ID_NAME = 'cells_IDs.dat'
POSITIONS_FOLDER = 'cell_positions'
POSITION_FILE_PROTO = 'cell_position_{:d}.dat'
FLOW_MATRIX_FILE = 'V1_flow_matrix_simNo_1_corrected.txt'
